on: push

name: 🚀 Deploy in Homologacao
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2.3.2

    - name: Use Node.js 12
      uses: actions/setup-node@v2-beta
      with:
        node-version: '12'
      
    - name: 🔨 Build Project
      run: |
        yarn
        yarn build
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: dbhomo-srv04.gojur.com.br
        username: ftpwebhomo.gojur.com.br|ftphomouser
        password: Ftphomo02289bc!!
        server-dir: /homo_inetpub/homo_wwwroot/GOJUR_APP/ 
